import { useEffect, useMemo, useState } from "react";
// import "./area-manager/WeeklyReport.css"; // TODO: Create this CSS file if needed

interface WeeklyReportRecord {
  id: number;
  securityOfficerName: string;
  securityId: string;
  companyName: string;
  weekNumber: number;
  month: number | null;
  year: number;
  weekStartDate?: string | null;
  weekEndDate?: string | null;
  branch?: string | null;
  totalShifts: number;
  totalOvertimeHours: number;
  totalHoursWorked: number;
  remarks: string | null;
  areaManagerName?: string | null;
  areaManagerEmployeeId?: string | null;
}

const MONTH_LABELS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

function weekDisplayLabel(r: WeeklyReportRecord): string {
  if (r.month != null && r.month >= 1 && r.month <= 12) {
    return "Week " + r.weekNumber + ", " + MONTH_LABELS[r.month - 1] + " " + r.year;
  }
  return "Week " + r.weekNumber + ", " + r.year;
}

export default function OperationalWeeklyReport() {
  const [allReports, setAllReports] = useState<WeeklyReportRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [filterCompany, setFilterCompany] = useState("");
  const [filterYear, setFilterYear] = useState<string>("");
  /** 1–12 or "" for all */
  const [filterMonth, setFilterMonth] = useState<string>("");
  /** 1–4 (week of month) or "" for all */
  const [filterWeekOfMonth, setFilterWeekOfMonth] = useState<string>("");
  const [viewReportItem, setViewReportItem] = useState<WeeklyReportRecord | null>(null);
  const [viewModalOpen, setViewModalOpen] = useState(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      setLoading(true);
      setLoadError(null);
      try {
        const res = await fetch("/api/weekly-reports/operational");
        if (!res.ok) throw new Error("Failed to load weekly reports");
        const data = await res.json();
        if (!cancelled) setAllReports(Array.isArray(data) ? data : []);
      } catch (e) {
        if (!cancelled) {
          setLoadError(e instanceof Error ? e.message : "Could not load reports");
          setAllReports([]);
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const companyOptions = useMemo(() => {
    const set = new Set<string>();
    for (const r of allReports) {
      if (r.companyName) set.add(r.companyName);
    }
    return Array.from(set).sort((a, b) => a.localeCompare(b));
  }, [allReports]);

  const yearOptions = useMemo(() => {
    const set = new Set<number>();
    for (const r of allReports) {
      if (r.year != null) set.add(r.year);
    }
    return Array.from(set).sort((a, b) => b - a);
  }, [allReports]);

  const filteredReports = useMemo(() => {
    const monthNum = filterMonth ? parseInt(filterMonth, 10) : null;
    const weekNum = filterWeekOfMonth ? parseInt(filterWeekOfMonth, 10) : null;
    return allReports.filter((r) => {
      if (filterCompany && r.companyName !== filterCompany) return false;
      if (filterYear && String(r.year) !== filterYear) return false;
      if (monthNum != null && monthNum >= 1 && monthNum <= 12) {
        if (r.month == null || r.month !== monthNum) return false;
      }
      if (weekNum != null && weekNum >= 1 && weekNum <= 4) {
        if (r.weekNumber == null || r.weekNumber !== weekNum) return false;
      }
      return true;
    });
  }, [allReports, filterCompany, filterYear, filterMonth, filterWeekOfMonth]);

  function viewReport(report: WeeklyReportRecord) {
    setViewReportItem(report);
    setViewModalOpen(true);
  }

  return (
    <div className="area-weekly">
      <div className="header">
        <h2>Weekly Reports</h2>
        <p>
          Reports generated by area managers from shift scheduling and attendance. This list updates as area managers
          generate or refresh weekly reports.
        </p>
      </div>

      <div className="content-wrapper">
        <h3 className="section-title">Filters</h3>
        <div className="form-grid" style={{ marginBottom: 8 }}>
          <div className="form-group">
            <label>Company</label>
            <select value={filterCompany} onChange={(e) => setFilterCompany(e.target.value)} style={{ minWidth: 200 }}>
              <option value="">All companies</option>
              {companyOptions.map((c) => (
                <option key={c} value={c}>
                  {c}
                </option>
              ))}
            </select>
          </div>
          <div className="form-group">
            <label>Year</label>
            <select value={filterYear} onChange={(e) => setFilterYear(e.target.value)} style={{ minWidth: 120 }}>
              <option value="">All years</option>
              {yearOptions.map((y) => (
                <option key={y} value={String(y)}>
                  {y}
                </option>
              ))}
            </select>
          </div>
          <div className="form-group">
            <label>Month</label>
            <select value={filterMonth} onChange={(e) => setFilterMonth(e.target.value)} style={{ minWidth: 140 }}>
              <option value="">All months</option>
              {MONTH_LABELS.map((label, i) => (
                <option key={i + 1} value={String(i + 1)}>
                  {label}
                </option>
              ))}
            </select>
          </div>
          <div className="form-group">
            <label>Week of month</label>
            <select
              value={filterWeekOfMonth}
              onChange={(e) => setFilterWeekOfMonth(e.target.value)}
              style={{ minWidth: 160 }}
            >
              <option value="">All weeks</option>
              <option value="1">Week 1 (days 1–7)</option>
              <option value="2">Week 2 (days 8–14)</option>
              <option value="3">Week 3 (days 15–21)</option>
              <option value="4">Week 4 (days 22–end)</option>
            </select>
          </div>
        </div>
        {loadError ? (
          <p style={{ color: "#b91c1c", marginTop: 8 }}>{loadError}</p>
        ) : null}
      </div>

      <div className="content-wrapper">
        <h3 className="section-title">Area manager weekly reports</h3>
        {loading ? (
          <p style={{ color: "#6b7280" }}>Loading…</p>
        ) : (
          <table className="reports-table">
            <thead>
              <tr>
                <th>Week</th>
                <th>Area manager</th>
                <th>Officer</th>
                <th>Security ID</th>
                <th>Company</th>
                <th>Shifts</th>
                <th>OT Hours</th>
                <th>Total Hours</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredReports.length === 0 ? (
                <tr>
                  <td colSpan={9} className="empty-state">
                    {allReports.length === 0
                      ? "No weekly reports yet. They appear here when area managers generate them."
                      : "No reports match your filters."}
                  </td>
                </tr>
              ) : (
                filteredReports.map((report) => (
                  <tr key={report.id}>
                    <td>{weekDisplayLabel(report)}</td>
                    <td>
                      {report.areaManagerName || "—"}
                      {report.areaManagerEmployeeId ? (
                        <span style={{ color: "#6b7280", fontSize: 12, display: "block" }}>
                          {report.areaManagerEmployeeId}
                        </span>
                      ) : null}
                    </td>
                    <td>{report.securityOfficerName}</td>
                    <td>{report.securityId}</td>
                    <td>{report.companyName}</td>
                    <td>
                      {report.totalShifts}{" "}
                      {report.totalShifts >= 15 ? (
                        <span className="badge badge-warning">High</span>
                      ) : (
                        <span className="badge badge-success">Normal</span>
                      )}
                    </td>
                    <td>{(report.totalOvertimeHours ?? 0).toFixed(2)}</td>
                    <td>{(report.totalHoursWorked ?? 0).toFixed(2)}</td>
                    <td>
                      <button type="button" className="btn-view" onClick={() => viewReport(report)}>
                        View details
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        )}
      </div>

      {viewModalOpen && viewReportItem && (
        <div className="modal-overlay" onClick={() => setViewModalOpen(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <h3>Weekly report details</h3>
            <div style={{ marginTop: 10, lineHeight: 1.7 }}>
              <div>
                <strong>Week:</strong> {weekDisplayLabel(viewReportItem)}
                {viewReportItem.weekStartDate && viewReportItem.weekEndDate
                  ? ` (${String(viewReportItem.weekStartDate).slice(0, 10)} → ${String(
                      viewReportItem.weekEndDate
                    ).slice(0, 10)})`
                  : ""}
              </div>
              <div>
                <strong>Area manager:</strong> {viewReportItem.areaManagerName || "—"}
                {viewReportItem.areaManagerEmployeeId ? ` (${viewReportItem.areaManagerEmployeeId})` : ""}
              </div>
              <div>
                <strong>Officer:</strong> {viewReportItem.securityOfficerName} ({viewReportItem.securityId})
              </div>
              <div>
                <strong>Company:</strong> {viewReportItem.companyName}
              </div>
              {viewReportItem.branch ? (
                <div>
                  <strong>Branch:</strong> {viewReportItem.branch}
                </div>
              ) : null}
              <div>
                <strong>Shifts (from scheduling):</strong> {viewReportItem.totalShifts ?? 0}
              </div>
              <div>
                <strong>OT Hours (from attendance):</strong> {(viewReportItem.totalOvertimeHours ?? 0).toFixed(2)}
              </div>
              <div>
                <strong>Total Hours Worked (from attendance):</strong>{" "}
                {(viewReportItem.totalHoursWorked ?? 0).toFixed(2)}
              </div>
              <div>
                <strong>Remarks:</strong> {viewReportItem.remarks?.trim() ? viewReportItem.remarks : "—"}
              </div>
            </div>

            <div style={{ display: "flex", justifyContent: "flex-end", gap: 12, marginTop: 18 }}>
              <button type="button" className="btn btn-secondary" onClick={() => setViewModalOpen(false)}>
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
