export interface Invoice {
  id: number;
  invoiceNo: string;
  clientId: number;
  clientName: string;
  clientAddress?: string;
  clientVatNo?: string;
  periodFrom: string;
  periodTo: string;
  issueDate: string;
  dueDate: string;
  status: 'DRAFT' | 'APPROVED' | 'ISSUED' | 'PENDING' | 'PAID' | 'OVERDUE' | 'CANCELLED';
  autoGenerated: boolean;

  oicStrength: number;
  jsoStrength: number;
  noOfShifts: number;
  oicRatePerShift: number;
  jsoRatePerShift: number;
  oicTotal: number;
  jsoTotal: number;

  subtotal: number;
  deductions: number;
  otherCharges: number;
  invoiceAmount: number;
  ssclAmount: number;
  vatAmount: number;
  totalPayable: number;

  internalNotes?: string;
  serviceLocation?: string;
}
